name: Build

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: eine/tip@master
      with:
        tag: nightly
        rm: true
        token: ${{ secrets.GITHUB_TOKEN }}
        files: libqbe.[ch]
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64
        vsversion: 2022
    - run: git config --global user.name "Patcher"
    - run: git config --global user.email "git@example.com"
    - run: python build_amalg.py
    - name: Update nightly release
